CREATE DATABASE HOSPITAL;

USE HOSPITAL;

CREATE TABLE DOCTOR(
     DNAME VARCHAR (25),
     DID VARCHAR (10) PRIMARY KEY,
     SPECIALITY VARCHAR (25)
);

INSERT INTO DOCTOR ( DNAME, DID, SPECIALITY)
VALUES
('ABIKO RESTY', 'D001', 'CARDIOLOGIST'),
('NAPASIRI JULIET', 'D002', 'THERAPIST'),
('TUKA ELLA', 'D003', 'DERMATOLOGIST');
 SELECT * FROM DOCTOR;
 

ALTER TABLE DOCTOR ADD COLUMN SALARY INT;
    